version: "3"

services:
  nginx:
    image: nginx:stable
    ports:
      - 8003:80
    expose:
      - "8003"
    volumes:
      - ./:/var/www/polyrhythms
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - default
      - nginx-proxy_nginx-proxy
    restart: always
    environment:
      - VIRTUAL_PORT=8003
      - VIRTUAL_HOST=polyrhythms.shirleyyin.com
      - LETSENCRYPT_HOST=polyrhythms.shirleyyin.com
      - LETSENCRYPT_EMAIL=contact@shirleyyin.com

networks:
  default:
    driver: bridge
  nginx-proxy_nginx-proxy:
    external: true
